### ISSUE TITLE
Dependency was DELETED !! COME ON !! PLZ HELP

### ISSUE THREAD

**Issue by wupmemo** [sinonjs/samsam#205]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* library version : sinon v 6.3.4
* Environment   : docker with yarn as the Package Manager

**What did you expect to happen?**
I was trying to deploy my backend normally with docker then i get a dependency failure 
**What actually happens**

**How to reproduce**
Simply use the version `6.3.4` of `sinon` then run yarn install. then you should see log

```
Trace: 
  Error: https://registry.yarnpkg.com/@sinonjs/samsam/-/samsam-2.1.0.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/Users/memo/.yarn/lib/cli.js:696:66)
      at new ResponseError (/Users/memo/.yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/Users/memo/.yarn/lib/cli.js:66996:16)
      at Request.emit (events.js:200:13)
      at Request.module.exports.Request.onRequestResponse (/Users/memo/.yarn/lib/cli.js:141441:10)
      at ClientRequest.emit (events.js:205:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
      at TLSSocket.socketOnData (_http_client.js:452:22)
      at TLSSocket.emit (events.js:200:13)
```

**Comment by mroderick** [comment]
There was a significant outage in the NPM registry yesterday.

See https://status.npmjs.org/incidents/cksjqc1w11v5

It has been resolved.
