### ISSUE TITLE
deepEqual throws an exception while comparing two jQuery objects on IE-11

### ISSUE THREAD

**Issue by nyk0r** [sinonjs/samsam#71]
* library version  : 3.3.2
* Environment   :  IE-11 
* Other libraries you are using: jQuery 3.4.1

**What did you expect to happen?**
deepEqual returns true as on any other browser.

**What actually happens**
"TypeError: Unable to get property 'length' of undefined or null reference" is thrown by getClassName.

**How to reproduce**

```javascript
import samsam from '@sinonjs/samsam';
import jQuery from 'jQuery';

console.log(
    samsam.deepEqual(
        jQuery('#test'),
        jQuery('#test')
    )
);
```

```
TypeError: Unable to get property 'length' of undefined or null reference
   at getClassName (http://localhost:1234/ie-11-bug.e31bb0bc.js:1004:9)
   at deepEqual (http://localhost:1234/ie-11-bug.e31bb0bc.js:1131:9)
   at deepEqualCyclic (http://localhost:1234/ie-11-bug.e31bb0bc.js:1068:5)
   at Anonymous function (http://localhost:1234/ie-11-bug.e31bb0bc.js:1257:9)
   at Anonymous function (http://localhost:1234/ie-11-bug.e31bb0bc.js:31912:1)
   at newRequire (http://localhost:1234/ie-11-bug.e31bb0bc.js:47:7)
   at Anonymous function (http://localhost:1234/ie-11-bug.e31bb0bc.js:81:7)
   at Global code (http://localhost:1234/ie-11-bug.e31bb0bc.js:8:1)
```

**Comment by fatso83** [comment]
NOt reproducible and no activity in two years. We also no longer support ie11
